spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/mall_template?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    ##url: jdbc:mysql://10.211.55.4:3306/mall_template?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    ## url: jdbc:mysql://10.211.55.4:3306/gulimall_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 3333

minio:
  endpoint: http://106.54.70.153:9000/ #Minio服务所在地址
  bucketName: malltemplate #存储桶名称
  accessKey: AKIAIOSFODNN7EXAMPLE #访问的key
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY #访问的秘钥
mall:
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCbq0LdwooqQjWEzxtJ+2NK4Q8OI6ENqlRJiy5rc7jS6dxAGaTCHl+oSYJ7uCltIo2lm69utfHiDtHyQUmeuUEMSVD5uj4SY4Tn4j4F37ufBL1FHryI9adTQ1cpaKf4Q8isWJMV/jIKt69pVvkBLq87aPNmdOhVrPuPbLOX73DMXxAKgj2YmSgz/yh/PsIcwGi4bMx/7LT+xHgk/XbLwFgEoRC2y0QKA/FSvUps2mnzozlDNuTiMvsATjlwSxpHad51Ukw4wI8aXH5rih7BgawHYwOXGCAdzPbp9pk2RWvTBX8/8we9gNx3NFZ1ZpqzRkmPKaM20W2XR4ePR6cvh/GtAgMBAAECggEBAJqiv+OmsrVT2/I4AfW2AWaKtvfmsL/waZY86jnXVMw/f4k1cBNdNMzpaPMZeB1va6INS3IAz20uJ6Qs8sL3aASaeBP6zFpb/dSTS+Vt4OUQQiv9Ym/zBuqRRG5gBit6ukdqHYKFZpR674cG3IguJegwU0l97KXfFm3dH3JYaoa4g4LzTx4A59Jn7y2mShTY/e/Q/CKVcM5xtkBSwnrYzU+PwPV/Qx8hUg9ugSLlMXBsVmqyan02p4mM9nba3GJrgfTZYUbeXQwSak3D8trILik+yhtfoRh2zeLMoGBKa7tOH/4OBSJLHdXUgsaf2R4gLVc+UwiJecjcx39cG5EkH4ECgYEAylg05E05HHhAJ9lQ/jNYGvhdBknw/sNB6ibQKt9pHcTzh3p2x+HQCWDUw7xEMoNFrfZCRvybVFO7MpVzBPrakKsg+DqGlCgt1OwpK39aZau3uxQGvpDA2llly6HQJaYBDY6q2rZzCz87/yf/rpXrpdazgYh3/S9+o4gJCqZ5of0CgYEAxPKRerq+1Jj2RsU5WlNEspo6tw65lLrT4Ssmh6X8rJMh9BQ2QEhN4sxubR/YgXxH9+IAdsuskWJGkTeX/2otn9DlWxH50kLF02Q4qFRlKla9+ttBJhAaZGzJosDv4gN8LWFKjd7rhvUgrROucZ+4WyH7W0MbHm55q10KdTEbhXECgYBQki79eYJ0Q63IMFB/6BH9K0hfaLH9v+JPSoU5jRxeLj6Kg8koblJYaaZPCnhdZMgqLRTXD18KhQzVZ40VPo4pbPsD3MoZ1KXrUt5R47QrJ+VRKPhGiX1BdLeEDjrDwwZIT7bYwC2vHM7XGyZEbo4WyxdPTPf6aR8UHub6xq9IQQKBgEKiAwBwADJzkhc9kPrzYzG+JpFapQUh9J+g9sc8LHHC0eD/mZ9EFz3dhprbBGhCwSKnzxpiLH9/rXpiQcXDia4hgge+3DP8LWwo41ZoP1YExQADgFY9aoCBofKzrjVckn3UBeJcAnnFo4mLOCDvNfN3WtB0ss8n93g34VrnA3WxAoGAT12WhgxKC51T/21tI9PuGCy9a1RHpYG20JyAKqlMB6QO50xf8Xsy4UeK6c8gkAiz9ycKvdSNYXFLEctgHBuaXVw9pVQeew+KfOLn5YGe+fce3XUwlZjqlTqL2ytvCgHOXTpZKB2vFxZmQT96dtB4HW0B0b3XGu2Nw/D7dEgpenA=
# 拦截器不拦截配置
interceptorconfig:
  path:
    #该路径下任何类型请求均不拦截
    include:
      - /api/users/register
      - /api/users/userInfo
      - /api/users/login
      - /api/users/loginOut
      - /api/goods/productHome
      - /api/goods/productDet
      - /api/goods/getProducts
      - /api/users/cartList
      - /error
      - /user
      - /api/admin/login
      - /api/admin/logout
      - /api/sys/getSysInfo
